### ISSUE TITLE
Add Missing Elements into UI

### ISSUE THREAD

**Issue by kieranhall** [dusk-network/dusk-explorer#3]
The current build does not currently output all of the required user interface elements according to [the designs](https://invis.io/35UPQ70QCYJ).

Actions needed:
- Add new placeholder components into the current UI app
- Rearrange existing components to represent the functionality described in the design
- Connect new components to a live data source

**Comment by kieranhall** [comment]
Currently all place holders are in and some basic styling applied.  As discussed yesterday, the plan now with this branch is to determine which placeholders can be connected to live data sources and which (for now will be hidden).

To be done: 
- Rebase this branch with master (in progress)
- @ggoranov to switch to this branch and confirm which data points we can connect and either do so, or give some guidance, so that I may pick it up.
- Finally merge branch back to master

**Comment by kieranhall** [comment]
This one is now waiting for merging (or perhaps replacing master) after being rebased.  @ggoranov is working on #6 which should connect up the missing data points.  For the time being the branch has all the dummy components commented out.

One point for @ggoranov is that the `LastTransactions` line 40 has a missing URL element for the block page. To retrieve this, the data model will need to be adjusted to allow the block hash to be used here.

**Comment by ggoranov** [comment]
With regard to latest changes, there are no placeholders for the new fields (keyimage and pubkey).  My suggestion is that this issue can be closed and for each missing component or found bug to report a separate github issue. By having smaller MR we'll ease the code review and decrease the amount of regressions.

**Comment by kieranhall** [comment]
Agreed.
